apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    harness.io/name: {{ .Values.delegateName | quote }}
  ports:
    - port: {{ .Values.grpcServiceConnectorPort }}
